### ISSUE TITLE
 History was not created

### ISSUE THREAD

**Issue by iagobragas** [Astroend/Albert-bot-Seguidor-de-sinais#7]
### Issue de histórico
Após as devidas entradas, ao final o histórico não é criado, as classes estão a seguir:
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/aa11e2ad007b19d6cf571b5700a3cbf4c3f23024/classes/action_functions.py#L51
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/aa11e2ad007b19d6cf571b5700a3cbf4c3f23024/classes/action_functions.py#L75
E as seguintes linhas fazem menção a elas:
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/8b9934e1012b819dc32ec222dd881eb8d65a6f62/main.py#L51
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/8fdb55660c035587bbab6a285a2ecfc9e60b09bf/classes/api_main.py#L206
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/8fdb55660c035587bbab6a285a2ecfc9e60b09bf/classes/api_main.py#L210
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/8fdb55660c035587bbab6a285a2ecfc9e60b09bf/classes/api_main.py#L229
https://github.com/Astroend/Albert-bot-Seguidor-de-sinais/blob/8fdb55660c035587bbab6a285a2ecfc9e60b09bf/classes/api_main.py#L232-L233

**Comment by lusqua** [comment]
Ao alterar a o local do arquivo referente ao processo (antes funcionava como multiprocesso), não foi passadas as classes referentes as WriteTXT e a variável não foi inicializada para o uso como é necessário.

![image](https://user-images.githubusercontent.com/43057423/150622340-bffd8092-87da-4706-b2a6-c548fd9e3afb.png)

Variáveis e declarações necessárias para o pleno funcionamento.
